---
title: 'Data 607: Final Project'
author: "Christina Valore"
date: "4/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Question: Is the time of the year predicitive of the NYC subway on-time perfromance?

I wonder if we could use this as an additional data set for avg monthly weather: https://www.weather.gov/media/okx/Climate/CentralPark/monthlyannualtemp.pdf

```{r}
# load data
data<- read.csv("https://raw.githubusercontent.com/ChristinaValore/stats-prob-606/master/Performance_NYCT.csv", header=TRUE, check.names = FALSE)

# subsetting the data to only pull out the OTP (ON TIME %) for individual subway lines
otp <-data[ which(data$PARENT_SEQ=='391690'), ]

# separate the indicator and name column to have the subway names listed individually
library(tidyr)
otp<-separate(otp,INDICATOR_NAME,into=c( "INDICATOR" , "NAME" ),sep="-")
otp$NAME<-as.factor(otp$NAME)

# remove columns that are not needed for this analysis
otp<- otp[c(-1:-4)]
```


```{r plots}
library(ggplot2)

summary(otp$MONTHLY_ACTUAL)
summary(otp$MONTHLY_TARGET)

# qualitative value - no need for a summary 
summary(otp$PERIOD_MONTH)

#aggregating the monthly on-time values by subway line 
month_mean<-aggregate(otp$MONTHLY_ACTUAL, by = list(otp$NAME), FUN=mean)
names(month_mean)<- c("LINE","AVG")

#Plotting the aggregate values to have a quick view of which subways have the best/worst time overall monthly
ggplot(month_mean,aes(x=reorder(LINE,-AVG), y= AVG)) + geom_bar(stat="identity") + theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```