---
title: 'Data 607: Final Project'
author: "Anthony Munoz, Christina Valore, David Apolinar"
date: "5/10/2019"
output: 
  html_document:
    #df_print: paged
    toc: true # table of content true
    toc_collapsed : false
    toc_float: true
    code_folding : show
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: true  ## if you want number sections at each table header
    smooth_scroll: true
    theme: cerulean  # many options for theme, this one is my favorite.
    highlight: textmate  # specifies the syntax highlighting style
---

```{r setup, include=FALSE}
library(mongolite)
library(magrittr)
library(dplyr)
library(tidyr)
```

# Project Overview

# Business Question

Is the time of the year predicitive of the NYC subway on-time perfromance (OTP)?

# Obtain the Data

Source: MTA

```{r MTA}
# load data
data<- read.csv("https://raw.githubusercontent.com/ChristinaValore/stats-prob-606/master/Performance_NYCT.csv", header=TRUE, check.names = FALSE)
# subsetting the data to only pull out the OTP (ON TIME %) for individual subway lines
otp <-data[ which(data$PARENT_SEQ=='391690'), ]
# separate the indicator and name column to have the subway names listed individually

otp<-separate(otp,INDICATOR_NAME,into=c( "INDICATOR" , "NAME" ),sep="-")
otp$NAME<-as.factor(otp$NAME)
# remove columns that are not needed for this analysis
otp<- otp[c(-1:-4)]
```

Source: https://www.weather.gov/media/okx/Climate/CentralPark/monthlyannualtemp.pdf
```{r weather}
## @David - please add in the weather data 
file <- "https://raw.githubusercontent.com/dapolloxp/607-finalproject/master/monthlyannualtemp-converted.csv"

weather.data = read.csv(file, stringsAsFactors = FALSE)
cleaned.weather <- weather.data %>% select(-11)
missing.days <- c(77.5, 76, 68.5, 57.5, 47.5, 38)
cleaned.weather[150,8:13] <- missing.days
cleaned.weather[150,14] <- apply(cleaned.weather[10,2:13],1,mean)

mongo_pwd_file <- "/Users/davidapolinar/Dropbox/CUNYProjects/Srping2019/Data607/Week 13/mongopassword.txt"

mongo_password <-read.delim(mongo_pwd_file, header = FALSE, stringsAsFactors = FALSE)

url <- paste0("mongodb://nyc.admin:", mongo_password$V1 , "@10.20.1.6:27017/weather",sep = "")

mgo <- mongo(collection = "nyc", db = "weather",  url=url, verbose = TRUE)
mgo$drop()
mgo$insert(cleaned.weather)

# Filter out

weather.above.2008<-mgo$find('{"YEAR":{"$gt":2007}}')

# Show collections
mgo$info()


weather.above.2008 <- weather.above.2008 %>% select(-ANNUAL)
wide.to.long <- gather(weather.above.2008, 'JAN', 'FEB', 'MAR', 'APR','MAY','JUN','JUL','AUG', 'SEP','OCT','NOV','DEC',key = 'Month', value = 'Avg Monthly Temp')

wide.to.long %>% arrange(YEAR)
```

```{r population}
## @Anthony - please add in the population data
```

# Cleansing

```{r}
## Once we have all the data - we can attempt to combine all a do a futher cleansing process as needed.
```


# Exploration

```{r ggplot}
library(ggplot2)
summary(otp$MONTHLY_ACTUAL)
summary(otp$MONTHLY_TARGET)
# qualitative value - no need for a summary 
summary(otp$PERIOD_MONTH)
#aggregating the monthly on-time values by subway line 
month_mean<-aggregate(otp$MONTHLY_ACTUAL, by = list(otp$NAME), FUN=mean)
names(month_mean)<- c("LINE","AVG")
#Plotting the aggregate values to have a quick view of which subways have the best/worst time overall monthly
ggplot(month_mean,aes(x=reorder(LINE,-AVG), y= AVG)) + geom_bar(stat="identity") + theme (axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

# Modeling 

# Interpreration

Is weather a predictor of the NYC subway's on time percentage (OTP)?

# Obtain the Data



# Cleansing

# Exploration

# Modeling 

# Interpreting

# Conclusion