---
title: "TEST"
author: "David Apolinar"
date: "5/5/2019"
output: html_document
---

```{r setup, include=FALSE}
library(mongolite)
library(magrittr)
library(dplyr)
library(tidyr)
# test
file.old <- "/Users/davidapolinar/Dropbox/CUNYProjects/Srping2019/Data607/FinalProject/monthlyannualtemp-converted.csv"
file <- "https://raw.githubusercontent.com/dapolloxp/607-finalproject/master/monthlyannualtemp-converted.csv"

weather.data = read.csv(file, stringsAsFactors = FALSE)
cleaned.weather <- weather.data %>% select(-11)
missing.days <- c(77.5, 76, 68.5, 57.5, 47.5, 38)
cleaned.weather[150,8:13] <- missing.days
cleaned.weather[150,14] <- apply(cleaned.weather[10,2:13],1,mean)

mongo_pwd_file <- "/Users/davidapolinar/Dropbox/CUNYProjects/Srping2019/Data607/Week 13/mongopassword.txt"

mongo_password <-read.delim(mongo_pwd_file, header = FALSE, stringsAsFactors = FALSE)

url <- paste0("mongodb://nyc.admin:", mongo_password$V1 , "@10.20.1.6:27017/weather",sep = "")

mgo <- mongo(collection = "nyc", db = "weather",  url=url, verbose = TRUE)
mgo$drop()
mgo$insert(cleaned.weather)

test<-mgo$find('{"YEAR":{"$gt":2007}}')

mgo$find('{"YEAR":{}}')
```

```{r}
test2 <- test %>% select(-ANNUAL)
new <- gather(test2, 'JAN', 'FEB', 'MAR', 'APR','MAY','JUN','JUL','AUG', 'SEP','OCT','NOV','DEC',key = 'Month', value = 'Avg Monthly Temp')

new %>% arrange(YEAR)
```



```{r}

library(rvest)
lego_movie <- read_html("http://worldpopulationreview.com/us-cities/new-york-city-population")
lego_movie

```